"""Explicit translations reviewed with neighboring tooltip/book lines."""
CONTEXT={
'tooltip.ironfurnaces.rainbow_gen1':'每刻將產生',
'tooltip.ironfurnaces.rainbow_gen2':'RF；前提是其他所有等級的熔爐皆正在發電',
'tooltip.ironfurnaces.rainbow_gen3':'每個等級至少要有一座正在運作的熔爐發電機，且其能量暫存區不能已滿。',
'tooltip.ironfurnaces.rainbow_gen4':'能量會從設為輸出的各面輸出，不會存入內部能量暫存區。',
'item.simplyswords.icewhispersworditem.tooltip4':'消耗飽食度，在你所在的位置',
'item.simplyswords.icewhispersworditem.tooltip5':'召喚暴風雪，使敵人減速，並對',
'item.simplyswords.icewhispersworditem.tooltip6':'%d 格內的敵人造成更高的傷害。',
'item.simplyswords.moltenedgesworditem.tooltip5':'發出強力咆哮，擊退並點燃',
'item.simplyswords.moltenedgesworditem.tooltip6':'附近的敵人。獲得抗性與猛攻效果，',
'item.simplyswords.moltenedgesworditem.tooltip7':'持續時間取決於命中的敵人數量。',
'item.simplyswords.wickpiercersworditem.tooltip5':'攻擊都能命中兩次，',
'item.simplyswords.wickpiercersworditem.tooltip6':'持續 %d 秒。',
'twilightforest.book.tfstronghold.2':'有趣的事物，讓我想繼續探索這個區域。\n\n§8[[下一篇]]§0\n\n我在黑暗森林中發現了一處要塞廢墟。這類要塞通常由騎士居住，但裡面沒有騎士，反而到處都是',
'twilightforest.book.tfstronghold.4':'取得一把強大的權杖，似乎能削弱黑暗森林的詛咒；而在基座上放置強大生物的戰利品，或許就能進入要塞主體。',
'tooltip.enigmaticlegacy.avariceScroll2':'§5使§6豬布林§5對你保持中立，即使',
'tooltip.enigmaticlegacy.avariceScroll3':'§5受到§6第二詛咒§5也不例外。與牠們以物易物時，',
'tooltip.enigmaticlegacy.avariceScroll4':'§5交換所得約增加 §6100%§5。',
'tooltip.enigmaticlegacy.avariceScroll5':'§5有 §6%1$s§6 的機率§5獲得 §61 顆綠寶石§5，',
'tooltip.enigmaticlegacy.avariceScroll6':'§5任何被擊殺的生物都可能掉落。',
'tooltip.enigmaticlegacy.cosmicScroll12':'§5額外造成 §6+%1$s §d傷害§5與 §6+%2$s §d擊退§5，',
'tooltip.enigmaticlegacy.cosmicScroll13':'§5對象為未被選中的玩家；你的近戰',
'tooltip.enigmaticlegacy.cosmicScroll14':'§5攻擊也會將他們點燃。',
'tooltip.enigmaticlegacy.theInfinitum9':'§5持握時，有 §6%1$s §d的機率§5讓原本',
'tooltip.enigmaticlegacy.theInfinitum10':'§5足以致命的傷害無法殺死你。',
}
cube=[
'§d主動技能：',
'§6- 將你傳送至三個主要維度之一的隨機位置。',
'§d冷卻時間：§6%1$s§6 秒',
'§d被動能力：',
'§5- §6+35%§d 疾跑速度',
'§5- §6+100%§d 游泳速度',
'§5- §6+60%§d 挖掘速度',
'§5- §6+40%§d 攻擊速度',
'§5- §6+1§d 幸運附魔等級',
'§5- §6+1§d 幸運值',
'§5- 傷害超過 §6%1$s§6 點§5的攻擊會被完全抵擋。',
'§5- 有 §635%§d 的機率§5偏轉襲來的攻擊或投射物。',
'§5- 受到近戰攻擊時，對攻擊者施加隨機負面效果。',
'§5- 每當你擊殺生物，就會獲得隨機增益效果。',
'§5- 不需要空氣也能呼吸。',
'§5- 免疫負面狀態效果。',
'§5- 免疫擠壓、墜落、碰撞、尖刺、傳送、火焰',
'§5  與熔岩傷害。',
'§5- 生命值高於 §61 點§5時，受到致命傷害仍可存活，',
'§5  並保留 §61 點生命§5。若生命值不高於 §61 點§5，則嘗試',
'§5  觸發主動技能以避開致命傷害。成功時會將你的',
'§5  生命值恢復至 §630%§5，並施加強力增益效果。',
]
CONTEXT.update({f'tooltip.enigmaticlegacy.theCube{i}':v for i,v in enumerate(cube,1)})
